<a href="https://colab.research.google.com/github/thecodemaster152/Diabates-prediction/blob/main/Diabates_prediction_using_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE DEPENDENCIES

In [ ]:
import numpy as np    # used to make numpy arrays
import pandas as pd   # used to make pandas data frame
from sklearn.preprocessing import StandardScaler    # used to standardize the vast range of data
from sklearn.model_selection import train_test_split     # as usual train test split
from sklearn import svm            # svm model
from sklearn.metrics import accuracy_score        # to check how accurate prediction is

Data collection and analysis

In [ ]:
diabates_dataset = pd.read_csv('diabetes.csv')

#printing some rows of dataset just to be sure it looks good
diabates_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
diabates_dataset.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
diabates_dataset.shape

(768, 9)

In [ ]:
# this was all about what data looks like
# now lets see some of the attributes of the data
diabates_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
diabates_dataset['Outcome'].value_counts()      # this will take the outcome column and check how many have 1 or 0 as the value, basically will tell you how many cases are daibatic

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
diabates_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [ ]:
X = diabates_dataset.drop('Outcome' , axis =1 )
Y = diabates_dataset['Outcome']

In [ ]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [ ]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
# now the main task of standardizing the data
scaler = StandardScaler()
scaler.fit(X)

StandardScaler()

In [ ]:
scaler.mean_

array([  3.84505208, 120.89453125,  69.10546875,  20.53645833,
        79.79947917,  31.99257812,   0.4718763 ,  33.24088542])

In [ ]:
scaler.scale_

array([  3.36738361,  31.95179591,  19.34320163,  15.94182863,
       115.16894926,   7.87902573,   0.33111282,  11.75257265])

In [ ]:
X_scaled = scaler.transform(X)
print(X_scaled)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [ ]:
X = X_scaled
Y = diabates_dataset['Outcome']      # although this particular line was not needed

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y , random_state=3)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

training the model

In [ ]:
classifier = svm.SVC(kernel='linear')

In [ ]:
# now lets train this SVM classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [ ]:
classifier.support_vectors_

array([[-5.47918591e-01,  6.60540923e-01,  6.66618252e-01, ...,
        -9.25568512e-01,  8.73187880e-01, -1.04154944e+00],
       [ 6.39947260e-01, -4.34859164e-01,  9.76804751e-01, ...,
         6.10154356e-01,  7.70503845e-01, -1.90671905e-01],
       [-5.47918591e-01, -4.66156309e-01, -2.63941247e-01, ...,
        -1.89436889e-01,  2.80304371e+00,  6.45913543e-02],
       ...,
       [ 1.23388019e+00,  1.44296956e+00,  1.90736425e+00, ...,
         7.11689753e-01, -9.26802852e-01,  8.30381132e-01],
       [-8.44885053e-01, -5.92934199e-02,  8.73409251e-01, ...,
         1.72704372e+00,  1.01513346e+00, -3.60847411e-01],
       [ 4.60143347e-02, -8.10424908e-01, -2.63941247e-01, ...,
         9.41978774e-04, -9.38883326e-01, -1.90671905e-01]])

In [ ]:
classifier.support_vectors_.shape

(312, 8)

Model evaluation

In [ ]:
X_train_predict = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_predict , Y_train)
print(training_data_accuracy)

0.7833876221498371

In [ ]:
X_test_predict = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_predict , Y_test)
print(testing_data_accuracy)

0.7337662337662337

Making a predictive system

In [ ]:
input_data = (1,103,30,38,83,43.3,0.183,33)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
input_data_scaled = scaler.transform(input_data_reshaped)
final_prediction = classifier.predict(input_data_scaled)
print(final_prediction)

[0]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [1]:
print("this is a print command just to check new commit from google colab onto github")

this is a print command just to check new commit from google colab onto github